// using System.Text;
// using System.Text.Json;
// using System.Text.RegularExpressions;
//
// namespace LhqHandleBarsTest.Code;
//
// [AttributeUsage(AttributeTargets.Class)]
// public class GeneratorTemplateAttribute(string itemTemplateName) : Attribute
// {
//     public string ItemTemplateName { get; set; } = itemTemplateName;
// }
//
// public abstract partial class GeneratorTemplate
// {
//     private const string _generatedHeader =
//         """
//         //------------------------------------------------------------------------------
//         // <auto-generated>
//         //     This code was generated by a tool - Localization HQ Editor.
//         //
//         //     Changes to this file may cause incorrect behavior and will be lost if
//         //     the code is regenerated.
//         // </auto-generated>
//         //------------------------------------------------------------------------------
//         """;
//
//    
//     public abstract string HandlebarsFile { get; }
//
//     protected Dictionary<string, object?> ExtraData { get; } = [];
//
//     protected virtual string GeneratedHeader => _generatedHeader;
//
//     public string SerializeExtraData()
//     {
//         var dataBuilder = new StringBuilder();
//
//         if (ExtraData.Count > 0)
//         {
//             dataBuilder.Append("{");
//
//             int i = 0;
//             var dataCount = ExtraData.Count;
//             foreach (var (key, value) in ExtraData)
//             {
//                 string valueStr = JsonSerializer.Serialize(value);
//
//                 dataBuilder.Append($"""
//                                     "{key}": {valueStr}
//                                     """);
//                 i++;
//                 if (i < dataCount)
//                 {
//                     dataBuilder.AppendLine(",");
//                 }
//             }
//
//             dataBuilder.Append("}");
//         }
//
//         return dataBuilder.ToString();
//     }
//
//     protected GeneratorTemplate SetExtraData<T>(string key, T? value)
//     {
//         ExtraData[key] = value;
//         return this;
//     }
//
//     protected GeneratorTemplate ClearExtraData()
//     {
//         ExtraData.Clear();
//         return this;
//     }
//
//     protected GeneratorTemplate RemoveExtraData(string key)
//     {
//         if (ExtraData.ContainsKey(key))
//         {
//             ExtraData.Remove(key);
//         }
//
//         return this;
//     }
//
//     public string Generate(Generator generator, ModelManager modelManager)
//     {
//         ArgumentNullException.ThrowIfNull(generator);
//         PrepareData(modelManager);
//         return generator.Generate(this, modelManager.LhqModelFileName);
//     }
//
//     protected virtual void PrepareData(ModelManager modelManager)
//     {
//         SetExtraData("header", GeneratedHeader);
//
//         var primaryLanguage = modelManager.ModelContext.GetPrimaryLanguage();
//         SetExtraData("primaryLanguage", primaryLanguage);
//     }
// }