//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool - Localization HQ Editor.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.Desktop.WinForms
{
	using System;
	using System.ComponentModel;
	using System.Linq;
	using System.Resources;
	using System.Reflection;
	using System.Globalization;
	using System.Runtime.CompilerServices;
	using System.Threading;

	[System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public partial class StringsContext: Template.Desktop.WinForms.BindableObject, IFormattable
	{
		private CultureInfo _culture;
		private CultureInfo _fallbackCulture;

		private StringsContext()
        {}

		public static ResourceManager ResourceManager { get; } = 
			new ResourceManager("Template.Desktop.WinForms.Resources.Strings",
				typeof(Template.Desktop.WinForms.Strings).Assembly);

		public const string PrimaryCulture = "en";

		public string[] AvailableCultures => new[] {
			"de","en","sk"
		};

		public CultureInfo FallbackCulture
        {
	        get
	        {
	            if (_fallbackCulture == null)
	            {
	                _fallbackCulture = new CultureInfo(PrimaryCulture);
	            }
	            return _fallbackCulture;
	        }
	        set
	        {
	            if ((value == null) || !AvailableCultures.Contains(value.Name))
	            {
	                throw new InvalidOperationException($"Unable to set fallback culture to '{value.Name}' which is not defined in available cultures!");
	            }

	            _fallbackCulture = value;
            }
	    }

		public static StringsContext Instance { get; } = new StringsContext();

		public CultureInfo Culture
        {
            get => _culture ?? (_culture = CultureInfo.CurrentUICulture);
            set
            {
                if (value == null)
                {
                    throw new ArgumentNullException("Culture must not be null");
                }

                if (value.Name == Culture.Name)
                {
                    return;
                }

                _culture = value;
                Thread.CurrentThread.CurrentUICulture = _culture;
                OnPropertyChanged(nameof(Culture));

				StringsBindingProxy.Instance.RefreshProperties();
            }
        }

		public string ToString(string format, IFormatProvider formatProvider)
        {
            return GetStringSafely(format);
        }

		public string GetStringSafely(string name)
        {
            if (name == null)
            {
                throw new ArgumentNullException(nameof(name));
            }

            string result = string.Empty;
            try
            {
                result = Culture == null ? ResourceManager.GetString(name) : ResourceManager.GetString(name, Culture);
                if (string.IsNullOrEmpty(result) && FallbackCulture != null)
                {
                    result = ResourceManager.GetString(name, FallbackCulture);
                }
            }
            catch (MissingManifestResourceException)
            {
                return $"???{name}.{Culture?.Name}???";
            }

            return result;
        }
	}

	[System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public static partial class StringsKeys
	{
		public static partial class Languages
		{
			/// <summary>
			/// Gets localized string similar to: German Language
			/// </summary>
			public const string de = "Languagesde";
			/// <summary>
			/// Gets localized string similar to: English Language
			/// </summary>
			public const string en = "Languagesen";
			/// <summary>
			/// Gets localized string similar to: Slovak Language
			/// </summary>
			public const string sk = "Languagessk";
		}
		
		public static partial class Messages
		{
			/// <summary>
			/// Gets localized string similar to: Hi {0}, we're glad you are using {1} at {2}
			/// </summary>
			public const string Title = "MessagesTitle";
			/// <summary>
			/// Gets localized string similar to: Welcome
			/// </summary>
			public const string Welcome = "MessagesWelcome";
		}
	}

	[System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public partial class Strings
	{
		public partial class Languages
		{
    		/// <summary>
    		/// Gets localized string similar to: German Language
    		/// </summary>
    		public static string de => StringsContext.Instance.GetStringSafely(StringsKeys.Languages.de);
    
    		/// <summary>
    		/// Gets localized string similar to: English Language
    		/// </summary>
    		public static string en => StringsContext.Instance.GetStringSafely(StringsKeys.Languages.en);
    
    		/// <summary>
    		/// Gets localized string similar to: Slovak Language
    		/// </summary>
    		public static string sk => StringsContext.Instance.GetStringSafely(StringsKeys.Languages.sk);
    
		}
		
		public partial class Messages
		{
    		/// <summary>
    		/// Gets localized string similar to: Hi {0}, we're glad you are using {1} at {2}
    		/// </summary>
    		public static string Title => StringsContext.Instance.GetStringSafely(StringsKeys.Messages.Title);
    
    		/// <summary>
    		/// Gets localized string similar to: Hi {0}, we're glad you are using {1} at {2}
    		/// </summary>
    		public static string TitleWithParams(object userName,object productName,object date) => string.Format(StringsContext.Instance.GetStringSafely(StringsKeys.Messages.Title), userName,productName,date);
    
    		/// <summary>
    		/// Gets localized string similar to: Welcome
    		/// </summary>
    		public static string Welcome => StringsContext.Instance.GetStringSafely(StringsKeys.Messages.Welcome);
    
		}
	}

	[System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public partial class StringsBindingProxy: Template.Desktop.WinForms.BindableObject
	{
	    private StringsBindingProxy() 
		{}

	    public static StringsBindingProxy Instance { get; } = new StringsBindingProxy();

		/// <summary>
		/// Gets localized string similar to: German Language
		/// </summary>
		public string Languagesde => StringsContext.Instance.GetStringSafely(StringsKeys.Languages.de);

		/// <summary>
		/// Gets localized string similar to: English Language
		/// </summary>
		public string Languagesen => StringsContext.Instance.GetStringSafely(StringsKeys.Languages.en);

		/// <summary>
		/// Gets localized string similar to: Slovak Language
		/// </summary>
		public string Languagessk => StringsContext.Instance.GetStringSafely(StringsKeys.Languages.sk);

		
		/// <summary>
		/// Gets localized string similar to: Hi {0}, we're glad you are using {1} at {2}
		/// </summary>
		public string MessagesTitle => StringsContext.Instance.GetStringSafely(StringsKeys.Messages.Title);

		/// <summary>
		/// Gets localized string similar to: Welcome
		/// </summary>
		public string MessagesWelcome => StringsContext.Instance.GetStringSafely(StringsKeys.Messages.Welcome);

	}

    public abstract class BindableObject : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
    
	    protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        public void RefreshProperties()
        {
            OnPropertyChanged(null);
        }
    }
}
