//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool - Localization HQ Editor.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScaleHQ.Windows.WinForms1
{
	using System;
	using System.Linq;
	using System.Resources;
	using System.Globalization;
	using System.Threading;

	[System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public partial class StringsContext: ScaleHQ.Windows.WinForms1.BindableObject, IFormattable
	{
		private CultureInfo _culture;
		private CultureInfo _fallbackCulture;
		private static readonly Lazy<StringsContext> _instance = new Lazy<StringsContext>(() => new StringsContext());
		private static readonly Lazy<ResourceManager> _resourceManager = new Lazy<ResourceManager>(CreateResourceManager);

		private StringsContext()
		{}

		public static ResourceManager ResourceManager
		{
			get
			{
				return _resourceManager.Value;
			}
		}

		public const string PrimaryCulture = "en";

		public string[] AvailableCultures => new[] {
			"de","en","sk"
		};

		public CultureInfo FallbackCulture
		{
			get
			{
				if (_fallbackCulture == null)
				{
					_fallbackCulture = new CultureInfo(PrimaryCulture);
				}
				return _fallbackCulture;
			}
			set
			{
				if ((value == null) || !AvailableCultures.Contains(value.Name))
				{
					throw new InvalidOperationException($"Unable to set fallback culture to '{value.Name}' which is not defined in available cultures!");
				}

				_fallbackCulture = value;
			}
		}

		public static StringsContext Instance
		{
			get
			{
				return _instance.Value;
			}
		}

		public CultureInfo Culture
		{
			get
			{
				return _culture ?? (_culture = CultureInfo.CurrentUICulture);
			}
			set
			{
				if (value == null)
				{
					throw new ArgumentNullException("Culture must not be null");
				}

				if (value.Name == Culture.Name)
				{
					return;
				}

				_culture = value;
				Thread.CurrentThread.CurrentUICulture = _culture;
				OnPropertyChanged(nameof(Culture));

				StringsBindingProxy.Instance.RefreshProperties();
			}
		}

		private static ResourceManager CreateResourceManager()
		{
			return new ResourceManager("ScaleHQ.Windows.WinForms1.Resources.Strings",
				typeof(ScaleHQ.Windows.WinForms1.Strings).Assembly);
		}

		public string ToString(string format, IFormatProvider formatProvider)
		{
			return GetStringSafely(format);
		}

		public string GetStringSafely(string name)
		{
			if (name == null)
			{
				throw new ArgumentNullException(nameof(name));
			}

			string result = GetStringSafely(name, Culture);
			if (result == null)
			{
				result = string.Format("???{0}.{1}???", name, Culture == null ? string.Empty : Culture.Name);
			}

			return result;
		}

		private string GetStringSafely(string name, CultureInfo culture)
		{
			string result = null;
			try
			{
				result = culture == null ? ResourceManager.GetString(name) : ResourceManager.GetString(name, culture);
			}
			catch (MissingManifestResourceException)
			{
				// Resource does not exist
			}

			return result;
		}
	}

	[System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public static partial class StringsKeys
	{
		public static partial class Cars
		{
			public static partial class Diesel
			{
				public static partial class Old
				{
					/// <summary>
					/// Gets localized string similar to: Old_ kia EN
					/// </summary>
					public const string Old_Kia = "CarsDieselOldOld_Kia";
				}
				/// <summary>
				/// Gets localized string similar to: Mercedes EN
				/// </summary>
				public const string Mercedes = "CarsDieselMercedes";
				/// <summary>
				/// Gets localized string similar to: Skoda EN
				/// </summary>
				public const string Skoda = "CarsDieselSkoda";
			}
			
			public static partial class Electric
			{
				/// <summary>
				/// Gets localized string similar to: toyota EN
				/// </summary>
				public const string ToyotaEV = "CarsElectricToyotaEV";
			}
		}
		
		public static partial class Messages
		{
			public static partial class Empty
			{
			}
			/// <summary>
			/// Gets localized string similar to: Hi {0}, we're glad you are using {1} at {2} / \ [ ] < > " & car <abc> </end>
			/// </summary>
			public const string Title = "MessagesTitle";
		}
		
		/// <summary>
		/// Gets localized string similar to: Welcome {0} in this {1} !
		/// </summary>
		public const string Welcome = "Welcome";
	}

	[System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public partial class Strings
	{
		public partial class Cars
		{
			public partial class Diesel
			{
				public partial class Old
				{
					/// <summary>
					/// Gets localized string similar to: Old_ kia EN
					/// </summary>
					public static string Old_Kia
					{
						get
						{
							return StringsContext.Instance.GetStringSafely(StringsKeys.Cars.Diesel.Old.Old_Kia);
						}
					}
			
				}
				/// <summary>
				/// Gets localized string similar to: Mercedes EN
				/// </summary>
				public static string Mercedes
				{
					get
					{
						return StringsContext.Instance.GetStringSafely(StringsKeys.Cars.Diesel.Mercedes);
					}
				}
		
				/// <summary>
				/// Gets localized string similar to: Skoda EN
				/// </summary>
				public static string Skoda
				{
					get
					{
						return StringsContext.Instance.GetStringSafely(StringsKeys.Cars.Diesel.Skoda);
					}
				}
		
			}
			
			public partial class Electric
			{
				/// <summary>
				/// Gets localized string similar to: toyota EN
				/// </summary>
				public static string ToyotaEV
				{
					get
					{
						return StringsContext.Instance.GetStringSafely(StringsKeys.Cars.Electric.ToyotaEV);
					}
				}
		
			}
		}
		
		public partial class Messages
		{
			public partial class Empty
			{
			}
			/// <summary>
			/// Gets localized string similar to: Hi {0}, we're glad you are using {1} at {2} / \ [ ] < > " & car <abc> </end>
			/// </summary>
			public static string Title
			{
				get
				{
					return StringsContext.Instance.GetStringSafely(StringsKeys.Messages.Title);
				}
			}
	
		}
		
		/// <summary>
		/// Gets localized string similar to: Welcome {0} in this {1} !
		/// </summary>
		public static string Welcome
		{
			get
			{
				return StringsContext.Instance.GetStringSafely(StringsKeys.Welcome);
			}
		}

		/// <summary>
		/// Gets localized string similar to: Welcome {0} in this {1} !
		/// </summary>
		public static string WelcomeWithParams(object userName,object productName,object date)
		{
			return string.Format(StringsContext.Instance.GetStringSafely(StringsKeys.Welcome), userName,productName,date);
		}

	}

	[System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public partial class StringsBindingProxy: ScaleHQ.Windows.WinForms1.BindableObject
	{
		private StringsBindingProxy() 
		{}

		public static StringsBindingProxy Instance { get; } = new StringsBindingProxy();

				/// <summary>
				/// Gets localized string similar to: Old_ kia EN
				/// </summary>
				public string CarsDieselOldOld_Kia
				{
					get
					{
						return StringsContext.Instance.GetStringSafely(StringsKeys.Cars.Diesel.Old.Old_Kia);
					}
				}
		
			/// <summary>
			/// Gets localized string similar to: Mercedes EN
			/// </summary>
			public string CarsDieselMercedes
			{
				get
				{
					return StringsContext.Instance.GetStringSafely(StringsKeys.Cars.Diesel.Mercedes);
				}
			}
	
			/// <summary>
			/// Gets localized string similar to: Skoda EN
			/// </summary>
			public string CarsDieselSkoda
			{
				get
				{
					return StringsContext.Instance.GetStringSafely(StringsKeys.Cars.Diesel.Skoda);
				}
			}
	
			
			/// <summary>
			/// Gets localized string similar to: toyota EN
			/// </summary>
			public string CarsElectricToyotaEV
			{
				get
				{
					return StringsContext.Instance.GetStringSafely(StringsKeys.Cars.Electric.ToyotaEV);
				}
			}
	
		
		/// <summary>
		/// Gets localized string similar to: Hi {0}, we're glad you are using {1} at {2} / \ [ ] < > " & car <abc> </end>
		/// </summary>
		public string MessagesTitle
		{
			get
			{
				return StringsContext.Instance.GetStringSafely(StringsKeys.Messages.Title);
			}
		}

		
		/// <summary>
		/// Gets localized string similar to: Welcome {0} in this {1} !
		/// </summary>
		public static string Welcome
		{
			get
			{
				return StringsContext.Instance.GetStringSafely(StringsKeys.Welcome);
			}
		}

		/// <summary>
		/// Gets localized string similar to: Welcome {0} in this {1} !
		/// </summary>
		public static string WelcomeWithParams(object userName,object productName,object date)
		{
			return string.Format(StringsContext.Instance.GetStringSafely(StringsKeys.Welcome), userName,productName,date);
		}

	}
}
