name: Build and publish UI App
description: Build and publish LHQ editor UI App
inputs:
  mode:
    description: 'Action mode: "publish" or "build_publish"'
    required: true
    default: 'build_publish'
  vpk_version:
    description: 'Version of the Velopack tool to use.'
    required: true
    default: '0.0.1369-g1d5c984'
  prerelease:
    description: 'Mark the published package as prerelease.'
    required: true
    default: 'true'
  release_name:
    description: 'Name of the release.'
    required: false
    default: ''
  release_tag:
    description: 'Tag of the release.'
    required: false
    default: ''
  new_version: 
    description: 'New version to set in the application.'
    required: false
    default: ''
  github_token:
    description: 'GitHub token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ "${{ inputs.mode }}" != "publish" && "${{ inputs.mode }}" != "build_publish" ]]; then
          echo "Error: 'mode' must be 'publish' or 'build_publish', got '${{ inputs.mode }}'"
          exit 1
        fi

        if [[ -z "${{ inputs.new_version }}" ]]; then
          echo "Error: 'new_version' input is required."
          exit 1
        fi

    - name: Check if release exists
      id: releaseInfo
      uses: actions/github-script@v7
      with:
        script: |
          const tag = '${{ inputs.release_tag }}';
          if (!tag) {
            core.setFailed(`Error: 'release_tag' input is required.`);
            return;
          }
          
          console.log(`Checking if release with tag '${tag}' exists...`);
          
          try {
            const { data: release } = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tag
            });
            
            console.log(`Release '${release.name}' with tag '${tag}' already exists.`);
            
            core.setOutput('releaseExist', true);
          } catch (error) {
            core.setOutput('releaseExist', false);
          }

    - name: Create new release
      if: steps.releaseInfo.outputs.releaseExist == 'false'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.release_tag }}
        name: ${{ inputs.release_name || inputs.release_tag }}
        body: ''
        append_body: true
        draft: false
        prerelease: ${{ inputs.prerelease }}

    - name: Install global tools
      shell: bash
      run: |
        echo "Installing VPK tool"
        dotnet tool install --global vpk --version ${{ inputs.vpk_version }}

    - name: Build and publish
      shell: pwsh
      run: | 
        $repoUrl = "https://github.com/${{ github.repository }}"
        $tagName = "${{ inputs.release_tag }}"
        $releaseName = "${{ inputs.release_name || inputs.release_tag }}"

        $psArgs = @{ repoUrl = $repoUrl; releaseName = $releaseName; tagName = $tagName; newVersion = "${{ inputs.new_version }}"; workingDir = "src/App"; ghToken = "${{ inputs.github_token }}" }
        if ("${{ inputs.mode }}" -eq "build_publish") { $psArgs['build'] = $true }
        if ("${{ inputs.prerelease }}" -eq "true") { $psArgs['prerelease'] = $true }
        & ./src/App/publish.ps1 @psArgs
