name: Build and publish UI App
description: Build and publish LHQ editor UI App
inputs:
  mode:
    description: 'Action mode: "publish" or "build_publish"'
    required: true
    default: 'build_publish'
  vpk_version:
    description: 'Version of the Velopack tool to use.'
    required: true
    default: '0.0.1369-g1d5c984'
  prerelease:
    description: 'Mark the published package as prerelease.'
    required: true
    default: 'true'
  release_name:
    description: 'Name of the release.'
    required: false
    default: ''
  release_tag:
    description: 'Tag of the release.'
    required: false
    default: ''
  new_version: 
    description: 'New version to set in the application.'
    required: false
    default: ''
  github_token:
    description: 'GitHub token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ "${{ inputs.mode }}" != "publish" && "${{ inputs.mode }}" != "build_publish" ]]; then
          echo "Error: 'mode' must be 'publish' or 'build_publish', got '${{ inputs.mode }}'"
          exit 1
        fi

        if [[ -z "${{ inputs.new_version }}" ]]; then
          echo "Error: 'new_version' input is required."
          exit 1
        fi

    - name: Check if release exists
      id: releaseInfo
      uses: actions/github-script@v7
      with:
        script: |
          const tag = '${{ inputs.release_tag }}';
          if (!tag) {
            core.setFailed(`Error: 'release_tag' input is required.`);
            return;
          }
          
          console.log(`Checking if release with tag '${tag}' exists...`);
          
          try {
            const { data: release } = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tag
            });
            
            console.log(`Release '${release.name}' with tag '${tag}' already exists.`);
            
            // Check if release has any assets
            if (release.assets && release.assets.length > 0) {
              console.log(`Release has ${release.assets.length} asset(s):`);
              release.assets.forEach(asset => console.log(`  - ${asset.name}`));
              core.setFailed(`Error: Release '${tag}' already exists and has ${release.assets.length} attachment(s).`);
              return;
            }
            
            console.log('Release exists but has no attachments. Proceeding...');
            core.setOutput('isPrerelease', release.prerelease.toString());
            core.setOutput('releaseName', release.name);
            core.setOutput('releaseTag', release.tag_name);
          } catch (error) {
            if (error.status === 404) {
              console.log(`Release with tag '${tag}' does not exist. Creating new release...`);
              
              const releaseName = '${{ inputs.release_name }}' || tag;
              const prerelease = '${{ inputs.prerelease }}' === 'true';
              
              const { data: newRelease } = await github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: tag,
                name: releaseName,
                prerelease: prerelease,
                draft: false
              });
              
              console.log(`Created new release '${newRelease.name}' with tag '${tag}' (prerelease: ${prerelease})`);
              core.setOutput('isPrerelease', prerelease.toString());
              core.setOutput('releaseName', newRelease.name);
              core.setOutput('releaseTag', newRelease.tag_name);
            } else {
              core.setFailed(`Error checking release: ${error.message}`);
            }
          }

    - name: Install global tools
      shell: bash
      run: |
        echo "Installing VPK tool"
        dotnet tool install --global vpk --version ${{ inputs.vpk_version }}

    - name: Build and publish
      shell: pwsh
      run: | 
        $repoUrl = "https://github.com/${{ github.repository }}"
        $releaseName = "${{ steps.releaseInfo.outputs.releaseName }}"
        $tagName = "${{ steps.releaseInfo.outputs.releaseTag }}"

        $psArgs = @{ repoUrl = $repoUrl; releaseName = $releaseName; tagName = $tagName; newVersion = "${{ inputs.new_version }}"; workingDir = "src/App"; ghToken = "${{ secrets.GITHUB_TOKEN }}" }
        if ("${{ inputs.mode }}" -eq "build_publish") { $psArgs['build'] = $true }
        if ("${{ steps.releaseInfo.outputs.isPrerelease }}" -eq "true") { $psArgs['prerelease'] = $true }
        & ./src/App/publish.ps1 @psArgs
