// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LHQ.VsExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = VsExtensionConstants.Id;
        public const string guidLhqEditorString = "07e76e77-f1fb-416c-aebc-03a6a40af16c";
        public const string guidPackageCmdSetString = "57ce79be-4b52-4ca1-a682-b1a3819793f5";
        public const string guidExtensionMenuString = "c1b6f4d9-396a-437c-b2cc-a46ad5f3fd0e";
        public static Guid guidPackage = new Guid(guidPackageString);
        public static Guid guidLhqEditor = new Guid(guidLhqEditorString);
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);
        public static Guid guidExtensionMenu = new Guid(guidExtensionMenuString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenu = 0x0001;
        public const int MyMenuGroup = 0x1020;
        public const int LicensingCommand = 0x0100;
        public const int OptionsCommand = 0x0200;
        public const int DuplicateElementCommand = 0x0201;
        public const int CopyElementAsSpecial1Command = 0x0202;
        public const int CopyElementAsSpecial2Command = 0x0203;
        public const int FindElementCommand = 0x0204;
        public const int NewCategoryCommand = 0x0206;
        public const int NewResourceCommand = 0x0207;
        public const int MainHelpCommand = 0x0208;
        public const int guidExtensionMenuGroup = 0x6000;
    }
}
